<a href="https://colab.research.google.com/github/Jannatu37/machine-learning-/blob/main/Simulation_and_Modeling_Lab_assignment_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Jannatul Ferdoss Faria

 ID: 2215151037

 University: University Of Information Technology And Science

 Section: 7A2

 Department: CSE

 Course Title: Simulation and Modeling Lab

 Course Code: CSE 413


Tasks:

Use numpy to create a 3×3 matrix of random integers between 1 and 50.  
   Run the code twice
  With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.  
  Without setting a seed, allowing random values to change each time.  
  Observe and explain the differences in outputs.  (in a different cell as text)


In [6]:
##Use numpy to create a 3×3 matrix of random integers between 1 and 50.
## Run the code twice

import numpy as np
matrix = np.random.randint(1, 51,(3, 3))
print(matrix)
print()
matrix = np.random.randint(1, 51,(3, 3))
print(matrix)

[[20  5 23]
 [ 5 39 44]
 [ 5 15 31]]

[[ 7 12 22]
 [17 31 28]
 [11 12 37]]


In [9]:
#With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.
import numpy as np
np.random.seed(10)
matrix = np.random.randint(1, 51,(3, 3))
print("Matrix with fixed seed :")
print(matrix)


Matrix with fixed seed :
[[10 37 16]
 [ 1 50 29]
 [26 30 49]]


In [13]:
##  Without setting a seed, allowing random values to change each time.
matrix_no_seed = np.random.randint(1, 51,(3, 3))
print("Matrix without setting a seed:")
print(matrix_no_seed)


Matrix without setting a seed:
[[31 26 13]
 [ 2 32 37]
 [28 19 30]]
